### ISSUE TITLE
Product page: Codes are displayed in front end

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Homestyle-Furniture#103]
IE7, IE8 & IE9 only
1. Create new subcategory
2. Input listed contents in the description box.
![image](https://cloud.githubusercontent.com/assets/11186313/7561196/a8de2ae6-f7fc-11e4-91c5-6a9b6994c9c7.png)

**Comment by genesiscebudigital** [comment]
Please Don't include codes in the content
![scree-shots](https://cloud.githubusercontent.com/assets/11186352/7605147/dab9f058-f97e-11e4-9c37-47769dcc9235.jpg)

**Comment by roseliesromeo** [comment]
I did not include codes in the content.  I don't do that.
I am still able to replicate the issue following the same steps.
1. Go to Admin - products categories http://homestylefurniture.stage.titanweb.com.au/wp-admin/edit-tags.php?taxonomy=product_cat&post_type=product
2. Add new product category
3. Save.
4. Check in front end (IE7, IE8 & IE9)
