### ISSUE TITLE
Admin - Form setting: Hidden field ID 6 form label should be "Form sent From".

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Homestyle-Furniture#15]
![image](https://cloud.githubusercontent.com/assets/11186313/7310703/3f47b058-ea63-11e4-86b7-83fc32239d9d.png)

**Comment by roseliesromeo** [comment]
Not fixed for Contact Us form

**Comment by roseliesromeo** [comment]
Form has been removed.

**Comment by genesiscebudigital** [comment]
What do you mean . ,it is ok in my end
![sentfrom](https://cloud.githubusercontent.com/assets/11186352/7719904/2374a700-fef9-11e4-83a4-f47011ac6ea5.png)
