### ISSUE TITLE
Admin - Customs Fields>Banner Page Link: Style options is not set to Stand "Standrd (WP metabox)".

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Homestyle-Furniture#2]
Per standards:
Always set the Options > Position to ‘Normal (after content)‘
Always set Options > Style to ‘Standard (WP metabox)’
![image](https://cloud.githubusercontent.com/assets/11186313/7292253/c117a1b6-e9cc-11e4-995f-9db6919b88b2.png)

**Comment by genesiscebudigital** [comment]
I removed the banner ACF Page link because it's useless.
