### ISSUE TITLE
Our products single page:  Details for variable product won't display in front end.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Homestyle-Furniture#26]
Task #30: Page content, Price, Variations
Above task is not implemented.

Currently, product variance won't show
Variance price won't display

![image](https://cloud.githubusercontent.com/assets/11186313/7311439/ede61b08-ea6e-11e4-8f42-1e908abc31d3.png)

**Comment by roseliesromeo** [comment]
Only the sale price will display.
Regular price won't display in both simple and variable product.

**Comment by genesiscebudigital** [comment]
if you switch to variable product . , the simple product price was auto delete by woocommerce default. , cannot display simple and variable product price together.

**Comment by roseliesromeo** [comment]
I am comparing different product data type.
One is simple product and the other is variable product.
