### ISSUE TITLE
Footer section: Font weight for the footer items should be regular as per design provided.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Homestyle-Furniture#34]
![image](https://cloud.githubusercontent.com/assets/11186313/7311998/d4f222f6-ea76-11e4-9fe7-7dfc554c7f52.png)

**Comment by genesiscebudigital** [comment]
It is regular/normal already . ,

**Comment by doylesee** [comment]
It was bold, so I'm removing the invalid label.
