### ISSUE TITLE
General: Task No. 4 - Banner ACF has not been implemented.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Homestyle-Furniture#4]
Currenlty, banner is still implemented as custom post.

![image](https://cloud.githubusercontent.com/assets/11186313/7293143/84e69d98-e9d4-11e4-8390-d924a3e0c743.png)

**Comment by roseliesromeo** [comment]
It is now implemented as repeater but currently placed in home page.

**Comment by genesiscebudigital** [comment]
banner has revert to custom post
