### ISSUE TITLE
Gallery page:  Pagination buttons is different from the other pages.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Homestyle-Furniture#86]
![image](https://cloud.githubusercontent.com/assets/11186313/7407686/760cde0e-ef47-11e4-8d4c-1c94856b4427.png)

**Comment by roseliesromeo** [comment]
Color scheme already matches but Previous and Next arrows are still different.

**Comment by genesiscebudigital** [comment]
clear cache

**Comment by roseliesromeo** [comment]
Still not match.  I already cleared cache.
