### ISSUE TITLE
Contact Us page: Submit button almost touches the Phone number field.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Homestyle-Furniture#90]
IE browsers
![image](https://cloud.githubusercontent.com/assets/11186313/7408567/77b56ede-ef50-11e4-9dfe-f6e9f63fd9a8.png)

**Comment by roseliesromeo** [comment]
Bottom of the Submit button is not aligned with the Select Location field unlike that of the other browsers.
![image](https://cloud.githubusercontent.com/assets/11186313/7745240/3098d530-ffdc-11e4-8981-13f038003331.png)

**Comment by genesiscebudigital** [comment]
It's ok in my end . , I always trying to fix without knowing the output . , if this is still not working , much better the developer there will fix . ,it is only a css fix

**Comment by roseliesromeo** [comment]
Still not fixed :)

**Comment by genesiscebudigital** [comment]
![ie10](https://cloud.githubusercontent.com/assets/11186352/7763632/794166b8-0076-11e5-966a-501b9e16b688.png)
